* inskcape jenkins docker build
Please not that this is a very early draft.

** Overview
There are several entities involved,a Host, and several docker containers.

The separation in several containers brings isolation and flexibility.

*** The host
The host runs several different docker containers, and is also responsible for 
shared disk space. 
*** The Jenkins Docker
Jenkins is run as a separate docker container, that is linked to docker build slaves.

This separation is intended to give an overview of all inkscape related builds from a single interface.


*** The build slave dockers
The are atm 2 build slaves, one for ubuntu and one for fedora.
These are controlled via ssha from the jenkins docker, via ssh.


** details
*** the jenkins docker container
https://registry.hub.docker.com/_/jenkins/

sudo mkdir /var/inkscape-jenkins
sudo chown 1000:1000 /var/inkscape-jenkins/
docker run --name inkscape-jenkins -p 18080:8080 -v /var/inkscape-jenkins:/var/jenkins_home jenkins


*** the fedora build
docker build
docker run 

*** the ubuntu build slave
see http://wiki.inkscape.org/wiki/index.php/Jenkins_server_setup
for the base dependencies.

