FROM fedora:20

RUN yum -y install ImageMagick-c++-devel ImageMagick-c++ ImageMagick-devel ImageMagick glibmm24-devel libsigc++-devel gtkmm24-devel glibmm24 libsigc++ gtkmm24 intltool gc gc-devel lcms lcms-devel gsl gsl-devel libxml2-devel libxslt-devel boost-devel popt-static poppler-devel inkscape
RUN yum -y install which
RUN yum -y install gcc gcc-g++ libtool  libtool-ltdl-devel
